### Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.


In [1]:
from sklearn.preprocessing import LabelEncoder

data = {
    'Color':('red', 'green', 'blue'),
     'Size' :('small','medium','large'),
      'Material':('wood','metal','plastic')
                                           }

In [4]:
import pandas as pd
df = pd.DataFrame(data)

In [5]:
df

Color    Size Material
0    red   small     wood
1  green  medium    metal
2   blue   large  plastic

In [9]:
# Initialize LabelEncoder

from sklearn.preprocessing import LabelEncoder


label_encoder = LabelEncoder()

In [11]:
encoded_data = df.apply(label_encoder.fit_transform)


In [12]:
print(encoded_data)


   Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1


### Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

In [13]:
import numpy as np

# Sample data for Age, Income, and Education Level
age = [30, 40, 50, 35, 45]
income = [50000, 60000, 70000, 55000, 65000]
education_level = [12, 16, 18, 14, 20]

# Create a numpy array with the data
data = np.array([age, income, education_level])

# Calculate the covariance matrix
covariance_matrix = np.cov(data)

print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[6.25e+01 6.25e+04 2.25e+01]
 [6.25e+04 6.25e+07 2.25e+04]
 [2.25e+01 2.25e+04 1.00e+01]]


### Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?
For "Gender", since there are only two categories (Male/Female), you can use binary encoding or label encoding. Binary encoding assigns 0 or 1 to each category, while label encoding assigns 0 and 1 arbitrarily to the categories. Either method can be used, but binary encoding might be preferred for its simplicity and clarity.

For "Education Level", since there is an ordinal relationship among the categories (High School < Bachelor's < Master's < PhD), you can use ordinal encoding. Ordinal encoding assigns numerical values based on the order or rank of the categories, preserving the ordinal relationship.

For "Employment Status", since there is no intrinsic order among the categories (Unemployed, Part-Time, Full-Time), you can use one-hot encoding. One-hot encoding creates binary columns for each category, indicating its presence or absence in each observation. This allows the model to learn the categorical nature of the variable without assuming any ordinal relationship.

### Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/East/West). Calculate the covariance between each pair of variables and interpret the results.

In [14]:
import numpy as np

# Sample data
temperature = [25, 28, 22, 24, 27]
humidity = [60, 65, 55, 58, 62]
weather_condition = [1, 0, 2, 1, 2]  # Sunny=0, Cloudy=1, Rainy=2
wind_direction = [0, 1, 2, 3, 0]  # North=0, South=1, East=2, West=3

# Create a numpy array with the data
data = np.array([temperature, humidity, weather_condition, wind_direction])

# Calculate the covariance matrix
covariance_matrix = np.cov(data)

print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[ 5.7   9.   -1.05 -1.8 ]
 [ 9.   14.5  -2.   -2.75]
 [-1.05 -2.    0.7  -0.05]
 [-1.8  -2.75 -0.05  1.7 ]]
